name: Build package
on: 
  workflow_dispatch:
    inputs:
      brh_name:
        description: '请输入该软件所在分支名称：'
        required: true
        type: string
      sf_name:
        description: '请输入该软件的名称：'
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout specific branch
      uses: actions/checkout@v4
      with:
        ref: "main"
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - name: build_number
      run: |
        python rc.py >> $GITHUB_ENV
    - name: Clean all checked out code 1
      run: |
        rm -rf "${{ github.workspace }}/*"
    - name: Checkout specific branch
      uses: actions/checkout@v4
      with:
        ref: "${{ github.event.inputs.brh_name }}"
    - name: Create zip file
      run: |
        echo ${{ env.RA_CO }}
        zip -r ${{ env.RA_CO }}.zip . -x '*.git*'
    - name: Upload
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ env.RA_CO }}.zip
        tag_name: index
    - name: Clean all checked out code 2
      run: |
        rm -rf "${{ github.workspace }}/*"
    - name: Checkout specific branch
      uses: actions/checkout@v4
      with:
        ref: "main"
    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Add key-value pair to JSON
      run: |
        KEY="${{ github.event.inputs.sf_name }}"
        VALUE="${{ env.RA_CO }}"
        jq --arg k "$KEY" --arg v "$VALUE" '. + {($k): $v}' test.json > temp.json && mv temp.json test.json
        python build.py
    - name: Commit and push changes
      run: |
        git config --local user.email "xumouren225588@163.com"
        git config --local user.name "xumouren225588"
        git add .
        git commit -m "Add key-value pair to JSON in Index.html"
        git push
