name: Build package
on: 
  workflow_dispatch:
    inputs:
      brh_name:
        description: '请输入该软件所在分支名称：'
        required: true
        type: string
      sf_name:
        description: '请输入该软件的名称：'
        required: true
        type: string
jobs:
  randomcode:
    runs-on: windows-latest
    steps:
    - name: Checkout specific branch
      uses: actions/checkout@v4
      with:
        ref: "main"
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - name: build_number
      run: |
        python rc.py >> $GITHUB_ENV
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout specific branch
      uses: actions/checkout@v4
      with:
        ref: "${{ github.event.inputs.brh_name }}"
    - name: Create zip file
      run: |
        zip -r ${{ env.RA_CO }}.zip . -x '*.git*'
    - name: Upload
      uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.RA_CO }}.zip
          tag_name: index